### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by Mefgalm** [Octonica/ClickHouseClient#10]
Hello. I'm trying to open connect via simple operation `connection.Open()` and always receive this error:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Octonica.ClickHouseClient.Exceptions.ClickHouseException: Internal error. Not supported message code (00000048) received from the server.
   at Octonica.ClickHouseClient.ClickHouseBinaryProtocolReader.ReadMessage(Boolean async, CancellationToken cancellationToken)
   at Octonica.ClickHouseClient.ClickHouseConnection.Open(Boolean async, CancellationToken cancellationToken)
   at Octonica.ClickHouseClient.Utils.TaskHelper.WaitNonAsyncTask(ValueTask task)
   at Octonica.ClickHouseClient.ClickHouseConnection.Open()
```

There are no problems with clickhouse. Another library is working fine with same connection parameters.

**Comment by SergeyMirvoda** [comment]
Hello, can you please send us your ClickHouse version?
```
select version()
```

**Comment by SergeyMirvoda** [comment]
Which port do you use?
Looks like you using HTTP port for binary connection.
Usually, port 9000 is used for TCP connection. 
Also, you can check your clickhouse server config ),

**Comment by Mefgalm** [comment]
Yep, 9000 port helped. Thanks.

**Comment by SergeyMirvoda** [comment]
@victor-sushko 
Victor, can we check this and throw more meaningful exception?

**Comment by victor-sushko** [comment]
There are two cases when an attempt to connect by HTTP will be detected:
1. Failed attempt to connect to the default HTTP port (8123);
2. Received 0x48 message code. Which stands for 'H' in the beginning of HTTP header.
