### ISSUE TITLE
Support "where in" queries

### ISSUE THREAD

**Issue by valeravorobjev** [Octonica/ClickHouseClient#13]
I've got a query:

`select * from data
where p1 in ({p1s}) and p2 in ({p2s}) and p3 in ({p3s})`

And this code:

`cmd.Parameters.AddWithValue("p1s", string.Join(",", p1s.Distinct()), DbType.String);` 

Don't work. Is there a way to run this query?

**Comment by victor-sushko** [comment]
For now there is no support for multiple values (array of values) in parameters.
But it's possible to get an array of values in the query:
```
select * from data where p1 in splitByChar(',', {p1s}) and p2 in splitByChar(',', {p2s}) and p3 in splitByChar(',', {p3s})
```

**Comment by SergeyMirvoda** [comment]
@victor-sushko 

> no support for multiple values

Something like?

```
var cmd = conn.CreateCommand("select * from data where p1 in ({p1s})");
var p = new ClickHouseParameter("p1s");
p.ClickHouseDbType = ClickHouseDbType.Array;
p.Value = new object[] { 1, 2, 3 };
cmd.Parameters.Add(p);
var r = cmd.ExecuteNonQuery();
```

But what about type of the array values?
In early npsql you had to use flagged enum for this i.e. ``ClickHouseDbType.Array | ClickHouseDbType.Int32``

**Comment by victor-sushko** [comment]
> But what about type of the array values?

I think that there should be the flag `IsArray` in `ClickHouseParameter`, which indicates that the parameter's value either an array or implements `IReadOnlyList<T>`.

**Comment by SergeyMirvoda** [comment]
@victor-sushko 

Original code should be rewritten as folows:
```
var cmd = conn.CreateCommand("select * from data where p1 in ({p1s})");
var p1s = cmd.Parameters.AddWithValue("p1s", p1s.Distinct(), DbType.String);
p1s.IsArray = true;
var r = await cmd.ExecuteReaderAsync();
```

Am I right?

@valeravorobjev 
Can you please upgrade to the latest nuget version and test your scenarios? 
Notice the string.Join is absent in the code above.

**Comment by SergeyMirvoda** [comment]
@victor-sushko 
can we set IsArray flag automatically, like in npgsql?

**Comment by victor-sushko** [comment]
> Original code should be rewritten as folows:
> 
> ```
> var cmd = conn.CreateCommand("select * from data where p1 in ({p1s})");
> var p1s = cmd.Parameters.AddWithValue("p1s", p1s.Distinct(), DbType.String);
> p1s.IsArray = true;
> var r = await cmd.ExecuteReaderAsync();
> ```
> 
> Am I right?

It's important to cast `IEnumerable<string>` to array or list. `IEnumerable<T>` is not supported in parameters.
Also consider to set the flag `IsNullable` to `false`. It will make the type of the parameter `Array(String)` instead of `Array(Nullable(String))`:
```
var cmd = conn.CreateCommand("select * from data where p1 in ({p1s})");
var p1s = cmd.Parameters.AddWithValue("p1s", p1s.Distinct().ToList(), DbType.String);
p1s.IsNullable = false;
var r = await cmd.ExecuteReaderAsync();
```

>can we set IsArray flag automatically, like in npgsql?

Actually, we do.
