### ISSUE TITLE
Unexpected NullReferenceException during connection closing.

### ISSUE THREAD

**Issue by Varfolomey** [Octonica/ClickHouseClient#16]
Hi there!

I have an error:

System.NullReferenceException
 at Octonica.ClickHouseClient.ClickHouseTcpClient.Dispose()
 at Octonica.ClickHouseClient.ClickHouseConnection.Dispose(Boolean disposing)
 at System.ComponentModel.Component.Finalize()

It throws from time to time and I can't understand why but I think null check in Dispose() would be nice anyway.

Something like that:

```
public void Dispose()
{
    _semaphore.Dispose();
    _reader.Dispose();
    _writer.Dispose();

    if(_client.Client != null)
        _client.Client.Close(0);
    
    _client.Dispose();
}
```

**Comment by SergeyMirvoda** [comment]
Hello, never seen this before even in pretty high load.
Can you please share your usage scenario?
Why you use semaphore?

**Comment by Varfolomey** [comment]
Hello Sergey!
Thanks for fast reply.

To be honest a can't show all code but I am following steps:

1. Create ClickHouseConnectionStringBuilder
```
_connectionBuilder = new ClickHouseConnectionStringBuilder
  {
      Host = options.Value.Host,
      Port = options.Value.Port,
      Database = options.Value.Database,
      User = options.Value.User,
      Password = options.Value.Password,
      CommandTimeout = options.Value.CommandTimeout
  };
```
2. Create connection and open it
```
var _connection = new ClickHouseConnection(_connectionBuilder);

if(_connection != null)
    await _connection.OpenAsync();
```

3. Create command
`var command = _connection.CreateCommand("SELECT CAST(COUNT(1), 'Int64') FROM UserTransactions WHERE UserId = 1"); `

4. Finally execute it 
`await command.ExecuteScalarAsync<long>(cancellationToken);`

It doesn't matter if command returns value or throws DB:Exception, after some timeout I receive NRE. 


In another scenario I'm using generic method to bind result to my objects. 
Maybe it could be better but it works fine and returns what I need.

 ```
public async IAsyncEnumerable<T> ExecuteQueryAsync<T>(
            string query,
            IDictionary<string, object> statements = null,
            [EnumeratorCancellation] CancellationToken token = default)
            where T : new()
        {
            await using var command = GetCommand(query, statements);
            var props = _scalars.Contains(typeof(T)) ? null : typeof(T).GetProperties()
                .Select((e, i) => new {Propery = e, DbName = e.Name.SnakeCase(), Index = i})
                .ToArray();

            await using var reader = await command.ExecuteReaderAsync(token);
            while (!token.IsCancellationRequested && await reader.ReadAsync(token))
            {
                T newObj = new T();
                if (props is {} && props.Length > 0)
                    foreach (var propertyRef in props)
                    {
                        var index = reader.GetOrdinal(propertyRef.DbName);
                        var type = reader.GetFieldType(index);
                        var data = reader.GetValue(index);
                        newObj.SetProperty(propertyRef.Propery, data, type);
                    }
                else
                    newObj = (T) reader.GetValue(0).ConvertFromDbValue(reader.GetFieldType(0));

                yield return newObj;
            }
        }
```
What am I doing wrong?

**Comment by Varfolomey** [comment]
Hello!

I have resolved the issue by disposing connection when command finished.

Thanks for fix anyway!

**Comment by SergeyMirvoda** [comment]
@Varfolomey 
You are welcome!
Thanks for the bug report!
