### ISSUE TITLE
Illegal type of column for parameter

### ISSUE THREAD

**Issue by Varfolomey** [Octonica/ClickHouseClient#17]
Hi!

I have Clickhouse table with some fields. One of them is 
![image](https://user-images.githubusercontent.com/7627898/107651801-f8c9d780-6c90-11eb-9977-143d2e522b49.png)

I'm trying to perform select statement:

```
var sb = new ClickHouseConnectionStringBuilder();
sb.Host = "127.0.0.1";
using var conn = new ClickHouseConnection(sb);
conn.Open();
using var cmd = conn.CreateCommand("SELECT * FROM MyTable WHERE {UserId}");
cmd.Parameters.AddWithValue("UserId", 1);
cmd.ExecuteReaderAsync()
....

```
Application sends proper parameter type
![image](https://user-images.githubusercontent.com/7627898/107653331-8e199b80-6c92-11eb-99a9-2c620e3bf6b1.png)

But after all that client throws exception: 

`DB::Exception: Illegal type Int32 of column for constant filter. Must be UInt8 or Nullable(UInt8).`

**Comment by SergeyMirvoda** [comment]
@Varfolomey 
Can you please share 
```
select version()
```
output from your ClickHouse server?

**Comment by Varfolomey** [comment]
@SergeyMirvoda 21.1.2

**Comment by SergeyMirvoda** [comment]
Hello!

Looks like you simply forgot to add column name in ``where``  instead of just {UserId} you should write
``UserId = {UserId}``

As for error: CH trying to interpret  1 as bool and int32 type is not compatible with CH bool representation requirements.

**Comment by Varfolomey** [comment]
@SergeyMirvoda omg. Thanks a lot, Sergey. It's my fault.
