### ISSUE TITLE
Command behavior "SequentialAccess, CloseConnection" not supported with Dapper Query

### ISSUE THREAD

**Issue by alec-anikin** [Octonica/ClickHouseClient#18]
Hi!

https://github.com/killwort/ClickHouse-Net/issues/53
I have the same issue with ClickHouseClient.

Thank you!

**Comment by victor-sushko** [comment]
Hello, Alec!

Support for different command behaviors was added to the version 1.1.8 (released today).

Supported flags:
1. `SchemaOnly`;
2. `SingleRow`;
3. `SingleResult`;
4. `SequentialAccess` (does not affect reader's behavior);
5. `CloseConnection`.

Not supported flags:
1. `KeyInfo`.

I've not tested this new feature with Dapper. But I hope it doesn't rely on the flag `KeyInfo`.
