### ISSUE TITLE
bulk insert support?

### ISSUE THREAD

**Issue by znyet** [Octonica/ClickHouseClient#20]
Hi @SergeyMirvoda!
ClickHouseClient support bulk insert?

ClickHouse.Ado bulk instert 1000000 records use 1.8 second! it is so fast!

if ClickHouseClient  can support it too,it will be very nice.

and thank you for your dapper par @ support in 1.1.9! good job.

**Comment by victor-sushko** [comment]
Hi, @znyet!

Yes, ClickHouseClient supports bulk insert. Here is a modified example form #19:
```C#
class Program
{
    record Person(int Id, string Name);
    static async Task Main(string[] args)
    {
        using var conn = new ClickHouseConnection("Host=click;Port=9000;Database=default;User=default;");
        conn.Open();
        using var cmd = conn.CreateCommand("CREATE TABLE IF NOT EXISTS dappertest(id Int32, name String) engine Memory");
        await cmd.ExecuteNonQueryAsync();

        List<int> ids = Enumerable.Range(1, 10_000).ToList();
        List<string> names = ids.Select(i => $"Name #{i}").ToList();

        //insert data
        await using (var writer = await conn.CreateColumnWriterAsync("insert into dappertest(id, name) values", default))
        {
            await writer.WriteTableAsync(new object[] { ids, names }, ids.Count, default);
        }

        //select data
        var result = await conn.QueryAsync<Person>("select * from dappertest");
    }
}
```

There is also an example with batching in [ColumnWriterBenchmarks](https://github.com/Octonica/ClickHouseClient/blob/master/src/Octonica.ClickHouseClient.Benchmarks/ColumnWriterBenchmarks.cs#L77).

**Comment by znyet** [comment]
thank you very much！
good project....
close it.
