### ISSUE TITLE
Supports IReadOnlyList<object> implementation for ColumnWriter

### ISSUE THREAD

**Issue by elmankross** [Octonica/ClickHouseClient#21]
Hello and thank you for the awesome client. Are there plans to implement `IReadOnlyList<object>` support for `CreateColumnWriter` inside type info? For example:
https://github.com/Octonica/ClickHouseClient/blob/de7d8d30292593d29541b88217d9311e8b18d08a/src/Octonica.ClickHouseClient/Types/UuidTypeInfo.cs#L38-L41
It may be useful when data is built at runtime and usually has an `object[][]` type. So the bulk insert method may looks like this:
```csharp
public async Task InsertManyAsync(string query, object[][] rowColumns)
{
   await using (var writer = await _connection.CreateColumnWriterAsync(query))
   {
      // here is no knowledge what is each collection about inside "rowColumns"
      await writer.WriteTableAsync(rowColumns, rowColumns.Length, default);
   }
}
``` 
This flow throws an exception now: `The type "System.Object" can't be converted to the ClickHouse type "UUID".`

**Comment by SergeyMirvoda** [comment]
@elmankross 
Thank you!

@elmankross 
But how we get the actual type of the column?
Testing (like Excel) first N elements is not an option, because of null.
Invent some type of ``valueFactory<T>`` to unpack from object also is not an option, because of late binding.

@victor-sushko 
Maybe old school overload with Dictionary<columnName:String, columnType:Type>?
Or ``Func`` for user-defined type provider for the column?

**Comment by elmankross** [comment]
@SergeyMirvoda, I think about a separate metadata object that stores column name and its type. Yup, old school :)

**Comment by SergeyMirvoda** [comment]
> @SergeyMirvoda, I think about a separate metadata object that stores column name and its type. Yup, old school :)

Maybe simple List<Type> is just enough where index equals to value index.

Also we need to invent or steal from somewhere a fast way to unbox value. TypeConverter.ChangeType very slow.

**Comment by victor-sushko** [comment]
Actually, elements of an unknown type are supported by `ClickHouseColumnWriter`. But this support is limited to the ancient interface `IEnumerable`. Target type `T` is the type of a column.
https://github.com/Octonica/ClickHouseClient/blob/de7d8d30292593d29541b88217d9311e8b18d08a/src/Octonica.ClickHouseClient/ClickHouseColumnWriter.cs#L533-L543

I am going to add similar type cast for interfaces `IReadOnlyList<object>`, `IList<object>`, `IEnumerable<object>` and `IAsyncEnumerable<object>`.

**Comment by elmankross** [comment]
I am sorry but when may occur support of `object[][]` for bulk insert?

**Comment by victor-sushko** [comment]
Hello, @elmankross!

Support of `object[][]` is partially implemented. I hope that full support of this feature will be ready at the end of this week.

I published pre-release nuget pacakge [1.1.11-rc](https://www.nuget.org/packages/Octonica.ClickHouseClient/1.1.11-rc). Maybe it will work in your case.

**Comment by elmankross** [comment]
@victor-sushko , it works for me. Thank you!

**Comment by victor-sushko** [comment]
Support for collection of objects was added in the version 1.1.12.
All items in a collection of objects (except `null` and `DBNull.Value`) must have the same type.

For example, there is a table
```SQL
CREATE TABLE some_table (
id Int64,
num Nullable(Int32),
ip IPv4) ENGINE = Memory
```

It is now possible to insert data to this table from `object[][]`.
```C#
var tableData = new object?[][] {
  new object[]{1, 2, 3, 4, 5, 6, 7},
  new object?[]{null, 598, -943, null, null, 7369, null},
  new object?[]{"192.168.121.0", DBNull.Value, "127.0.0.1", DBNull.Value, DBNull.Value, "10.0.0.1", "8.8.8.8"}
};

await using var writer = await connection.CreateColumnWriterAsync($"INSERT INTO some_table(id, num, ip) VALUES", CancellationToken.None);

// A type must be explicitly specified if the real type of inserted data is not equal to the type of a table's field.
writer.ConfigureColumn(0, new ClickHouseColumnSettings(tableData[0][0]!.GetType()));
writer.ConfigureColumn(2, new ClickHouseColumnSettings(tableData[2][0]!.GetType()));

await writer.WriteTableAsync(tableData, tableData[0].Length, CancellationToken.None);
```
