### ISSUE TITLE
Передача массива в качестве параметра

### ISSUE THREAD

**Issue by f1lareon6** [Octonica/ClickHouseClient#22]
@victor-sushko, @SergeyMirvoda  
Добрый день.
Подскажите пожалуйста, имеется ли возможность передать массив в качестве параметра?

Пробую такой вариант:
`await using var cmd = connection.CreateCommand("select * from numbers(100) where number in {p}");`
`var array = new[] {4, 8, 15, 16, 23, 42};`
`cmd.Parameters.AddWithValue("p", array);`
`var reader = await cmd.ExecuteReaderAsync();`

Получаю ошибку:
`Unhandled exception. Octonica.ClickHouseClient.Exceptions.ClickHouseServerException: DB::Exception: CAST AS Array can only be perforamed between same-dimensional Array or String types: while executing 'FUNCTION in(number : 0, _subquery26 :: 1) -> in(number, _su
bquery26) UInt8 : 2'`

**Comment by SergeyMirvoda** [comment]
Добрый!

Был недавно такой пример где-то здесь в задачах.
Сейчас поищу

**Comment by SergeyMirvoda** [comment]
Вот #13 

Но ошибка то от КХ приходит, что-то с типами его не устраивает.

А попробуйте взять в скобки  {p}

``select * from numbers(100) where number in ({p})``

**Comment by SergeyMirvoda** [comment]
В общем это непонятно как может работать вообще.
IN это оператор и он хочет аргументы через запятую, а у нас это массив.
КХ интересная штука и он иногда пытается догадаться, что хочет пользователь, но лучше на эту магию не надеяться и использовать функций ``has``, вот, например, так
```
 using var cmd = conn.CreateCommand("select * from numbers(100) where has({p}, toInt32(number))");
            var array = new[] {4, 8, 15, 16, 23, 42};
            cmd.Parameters.AddWithValue("p", array);
            var reader = await cmd.ExecuteReaderAsync();
            while (reader.Read())
            {
                System.Console.WriteLine(reader.GetValue(0));
            }
```

**Comment by f1lareon6** [comment]
При этом, код из тестов выполняется без ошибок:
`await using var cmd = connection.CreateCommand("SELECT {p}");`
`var expectedResult = new[] {4, 8, 15, 16, 23, 42};`
var param = cmd.Parameters.AddWithValue("p", expectedResult);`
var result = await cmd.ExecuteScalarAsync();`

Т.е. ошибка возникает при использовании параметра в условии IN

**Comment by SergeyMirvoda** [comment]
Именно так.
Это КХ не смог, и понятно почему.

**Comment by f1lareon6** [comment]
Спасибо за столь быстрый ответ.
Подскажите, а что вы имеете в виду под перегрузками?

**Comment by SergeyMirvoda** [comment]
Основная задача КХ (как они мне её озвучивали) работать максимально быстро и ради этого они идут на различные ухищрения.

Например, ваш пример вполне мог бы сработать, если бы оптимизатор КХ, решил бы что ваш параметр это константа и развернул бы её в список аргументов, тогда оператор IN выполнился бы.
т.е переписали бы код из ()
```
let p = [1,2,3]
let cmd = 'select * from numbers(100) where number in p'
```

в 
```
let cmd = 'select * from numbers(100) where number in array(1,2,3)'
```

Перегрузки (возможности вызова) ``IN`` для массива (как собственно и такого варианта использования) я в документации не нашёл, но это точно работало и иногда срабатывает, как раз из-за магических ускоряторов.

Следовательно это недокументированная функция, а вызывающая сторона (клиент) не должен на них надеяться:)

**Comment by f1lareon6** [comment]
Понял. Спасибо за ответ. 
Есть ещё один вопрос. Я сейчас пробую различные варианты работы и наткнулся на такую особенность.
Выполняю запрос 
`SELECT id from replacing_table where has({p}, uniq_id)`, где в качестве {p} передаю массив из 100000 элементов.
Первые 40000 возвращаются очень быстро. Затем идёт какое-то ожидание (около минуты) в строке `await reader.ReadAsync()`. Затем опять быстро получаются следующие 40000 записей и опять ожидание. Подскажите, с чем это связано и как можно решить эту проблему?

**Comment by SergeyMirvoda** [comment]
А приведите пример кода?

Вот мой пример
```
            var sb = new ClickHouseConnectionStringBuilder();
            sb.Database = "default";
            sb.Host = "click";

            sb.ReadWriteTimeout = 100000;
            sb.CommandTimeout = 100000;

            using var conn = new ClickHouseConnection(sb.ToString());
            await conn.OpenAsync();
            using var cmd = conn.CreateCommand("select toInt32(number) from numbers(100000) where has({p}, toInt32(number))");
            var array = Enumerable.Range(0, 100_000).ToArray();
            cmd.Parameters.AddWithValue("p", array);
            var reader = await cmd.ExecuteReaderAsync();
            var r = 0;
            var sw = Stopwatch.StartNew();
            while (reader.Read())
            {
                var i = reader.GetInt32(0);
                r += (int)i;
            }
            Debug.WriteLine(sw.Elapsed);
            Debug.WriteLine(r);

```

Выполняется за 30с, это тоже как-то медленно, но минута.

Может у вашего КХ мало памяти?

**Comment by f1lareon6** [comment]
`
            ClickHouseConnection connection = new ClickHouseConnection("Host=<host>;Port=9000;User=default;Database=default;CommandTimeout=600;");
            await connection.OpenAsync();
            await using var cmd = connection.CreateCommand("SELECT ID from replacing_table where has({p}, UNIQ_ID)");
            cmd.Parameters.AddWithValue("p", ids);
            await using var reader = await cmd.ExecuteReaderAsync();
            var list = new List<long>();
            while (await reader.ReadAsync())
            {
                list.Add(reader.GetInt64(0));
            }
            
            await connection.CloseAsync();
`

**Comment by f1lareon6** [comment]
В общем быстрее всего работает такой вариант:
```
ClickHouseConnection connection = new ClickHouseConnection(config.ConnectionString);
            await connection.OpenAsync();            
            var array = Enumerable.Range(0, 100_000).ToArray();            
            using var cmd = connection.CreateCommand("select toInt32(number) from numbers(100000) where toInt32(number) in splitByChar(',', {p})");
            cmd.Parameters.AddWithValue("p", string.Join(",", array));            
            await using var reader = await cmd.ExecuteReaderAsync();
            var list = new List<long>();            
            var sw = Stopwatch.StartNew();
            while (await reader.ReadAsync())
            {
                list.Add(reader.GetInt64(0));
            }
            Console.WriteLine(sw.Elapsed);
            await connection.CloseAsync();
```
250 миллисекунд
