### ISSUE TITLE
Длительное ожидание во время получения данных из БД

### ISSUE THREAD

**Issue by f1lareon6** [Octonica/ClickHouseClient#23]
@SergeyMirvoda 
Добрый день.
Я сейчас пробую различные варианты работы и наткнулся на такую особенность.
Выполняю запрос
`SELECT id from replacing_table where has({p}, uniq_id)`, где в качестве `{p}` передаю массив из 100000 элементов.
Первые 40000 возвращаются очень быстро. Затем идёт какое-то ожидание (несколько минут) в строке await reader.ReadAsync(). Затем опять быстро получаются следующие 40000 записей и опять ожидание. Подскажите, с чем это связано и как можно решить эту проблему?

**Comment by f1lareon6** [comment]
Быстрее всего работает такой вариант:
```
ClickHouseConnection connection = new ClickHouseConnection(config.ConnectionString);
            await connection.OpenAsync();            
            var array = Enumerable.Range(0, 100_000).ToArray();            
            using var cmd = connection.CreateCommand("select toInt32(number) from numbers(100000) where toInt32(number) in splitByChar(',', {p})");
            cmd.Parameters.AddWithValue("p", string.Join(",", array));            
            await using var reader = await cmd.ExecuteReaderAsync();
            var list = new List<long>();            
            var sw = Stopwatch.StartNew();
            while (await reader.ReadAsync())
            {
                list.Add(reader.GetInt64(0));
            }
            Console.WriteLine(sw.Elapsed);
            await connection.CloseAsync();
```
250 миллисекунд

**Comment by victor-sushko** [comment]
Добрый день!

Похоже, запрос выполняется медленно из-за размера массива. Если выполнить вставку данных во временную таблицу, а затем использовать эту таблицу в подзапросе с оператором `IN`, то такой запрос будет выполнен намного быстрее.
```SQL
CREATE TABLE temp_table(id UInt64) ENGINE = Memory
```
```C#
await using (var writer = await conn.CreateColumnWriterAsync($"INSERT INTO temp_table VALUES", CancellationToken.None))
{
  await writer.WriteTableAsync(new[] { Enumerable.Range(0, 100_000).Select(i => (uint)i) }, 100_000, CancellationToken.None);
}

var cmd = conn.CreateCommand($"select toInt32(number) from numbers(100000) where number in (select id from temp_table)");
await using var reader = await cmd.ExecuteReaderAsync();

while (await reader.ReadAsync())
{
// Чтение данных
}
```

Такой подход по очевидным причинам неудобен. Для такого случая пригодилась бы поддержка табличных параметров (#24).
