### ISSUE TITLE
Производительность при вставке

### ISSUE THREAD

**Issue by f1lareon6** [Octonica/ClickHouseClient#25]
Добрый день.
Выполняю bulk insert. Таблица из 700 колонок. Кол-во записей в одной вставке 50000. Время вставки ~ 50 секунд.
При этом, clickhouse-клиент, который работает поверх http то же самое делает ~ 15 сек.
Подскажите пожалуйста, существуют ли какие-либо настройки, позволяющие увеличить производительность insert`ов?

Метод, который вызывается для insert`ов:
```
public async Task BulkInsert(string tableName, string[] columnNames, object[][] rows)
        {
            var sw = new Stopwatch();
            sw.Start();
            
            var list = new List<object[]>();
            for (int i = 0; i < columnNames.Length; i++)
            {
                list.Add(rows.Select(x => x[i]).ToArray());
            }
            
            Console.WriteLine($"provider - {sw.Elapsed}");
            
            await using var connection = await CreateConnection();
            await using var writer = await connection.CreateColumnWriterAsync(
                $"INSERT INTO {tableName}({string.Join(",", columnNames)}) values", CancellationToken.None);
            await writer.WriteTableAsync(list, rows.Length, CancellationToken.None);
            
            Console.WriteLine($"provider - {sw.Elapsed}");
        }
```

**Comment by SergeyMirvoda** [comment]
А попробуйте выключить сжатие.
Возможно на это тратится время

``Compress`` у ConnectionStringBuilder'a

**Comment by victor-sushko** [comment]
Добрый день.

Есть два способа ускорить вермя вставки.
1. Отключить сжатие данных. Для этого в строке соединения нужно указать `Compress=false`. Запрос будет формироваться быстрее, но размер отправляемых данных увеличится.
2. Отправлять данные по частям. Оптимальный размер части (в строках) зависит от данных, подбирается эмпирически. Ниже приведён пример со вставкой блоков по 900 строк каждый.

```C#
public async Task BulkInsert(string tableName, string[] columnNames, object[][] rows)
{
    var swPrepareData = new Stopwatch();
    var swProvider = new Stopwatch();
    
    const int maxBatchSize = 900;
    var list = new List<object[]>(columnNames.Length);
    for (int i = 0; i < columnNames.Length; i++)
    {
        list.Add(new object[maxBatchSize]);
    }

    swProvider.Start();

    await using var connection = await CreateConnection();
    await using var writer = await connection.CreateColumnWriterAsync(
        $"INSERT INTO {tableName}({string.Join(",", columnNames)}) values", CancellationToken.None);

    swProvider.Stop();

    int count = 0;
    while (count < rows.Length)
    {
        swPrepareData.Start();
        var batchSize = Math.Min(maxBatchSize, rows.Length - count);

        for (int i = 0; i < columnNames.Length; i++)
        {
            var buffer = list[i];
            for (int j = 0; j < batchSize; j++)
                buffer[j] = rows[count + j][i];
        }

        count += batchSize;
        swPrepareData.Stop();
                
        swProvider.Start();
                
        await writer.WriteTableAsync(list, batchSize, CancellationToken.None);

        swProvider.Stop();
    }

    Console.WriteLine($"prepareData - {swPrepareData.Elapsed}; provider - {swProvider.Elapsed}");
}
```

**Comment by SergeyMirvoda** [comment]
@victor-sushko 

Может ``true`` по умолчанию убрать из строки соединения?

**Comment by f1lareon6** [comment]
Благодарю за ответ.
Отключив сжатие время увеличилось ~ до 2 минут.
Отправляя данные по частям (1000 строк) время сократилось до 17 секунд.

**Comment by victor-sushko** [comment]
> Может `true` по умолчанию убрать из строки соединения?

Лучше не надо.
1. Отключение сжатия не обязательно даст прирост производительности.
2. Вместе со сжатием отключаются контрольные суммы. Если есть возможность, то [от контрольных сумм не следует отказываться](https://habr.com/ru/company/oleg-bunin/blog/497334/).

А вот автоматическое разбиение большого пакета данных на части имеет смысл (#26).

**Comment by f1lareon6** [comment]
Ещё подскажите пожалуйста.
Нужно ли как-то контролировать коннекшены? Держать пулл коннекшенов и самостоятельно закрывать/освобождать их? Нужно ли как-то ограничивать кол-во открытых соединений?
Т.е. есть ли тут какие-то особенности? Достаточно ли будет перед каждым запросом создавать новое соединение в using, выполнять запрос и надеяться на сборщик мусора?

**Comment by victor-sushko** [comment]
> Нужно ли как-то контролировать коннекшены? Держать пулл коннекшенов и самостоятельно закрывать/освобождать их? Нужно ли как-то ограничивать кол-во открытых соединений?

Каких-то общих рекомендаций нет, всё зависит от ситуации.

>Т.е. есть ли тут какие-то особенности? Достаточно ли будет перед каждым запросом создавать новое соединение в using, выполнять запрос и надеяться на сборщик мусора?

Каждый объект `ClickHouseConnection` открывает сетевое соединение. А при освобождении ресурсов (при вызове одного из методов `Close` или `Dispose`) это соединение закрывает.

С управляемыми (managed) ресурсами соединения (буферы для чтения/записи данных, обычные массивы байт) сборщик мусора справляется, так что `using`'а должно быть достаточно.

**Comment by SergeyMirvoda** [comment]
>кол-во открытых соединений

Сам КХ ничего такого не требует, коннекции создаётся быстро, инициализации какой-то или огромных кэшей (как в постгресе) у них вроде бы нет, транзакций, тоже нет т.е. они дешёвые. 
Кэшировать их по идее есть смысл когда их просто очень много и они очень короткие, когда будет заметен лаг уже на уровне tcp (что-то типа http connection keep-alive)

Единственное, про сеть что мне встречалось в мануале, это рекомендации переходить на 10Гб ethernet
