### ISSUE TITLE
Вставка Guid-значения

### ISSUE THREAD

**Issue by f1lareon6** [Octonica/ClickHouseClient#29]
Добрый день.
Вставляю запись с Guid = 74D47928-2423-4FE2-AD45-82E296BF6058
Получаю данные из таблицы, а в ней Guid = 2879D474-2324-E24F-AD45-82E296BF6058
Последние две части совпадают, а в первых трёх числа смещены.
Подскажите, в чём проблема?

**Comment by SergeyMirvoda** [comment]
>Последние две части совпадают, а в первых трёх числа смещены.

Жуть какая, а в CH тип колонки какой?

**Comment by f1lareon6** [comment]
> Жуть какая, а в CH тип колонки какой?

UUID

**Comment by SergeyMirvoda** [comment]
@victor-sushko 

он ведь не смещён, а как будто тупоконечники встретились с остроконечниками!

Байты местами поменялись. Недавно только про это говрили, что вроде бы дотнет это сам должен делать.

@f1lareon6 

какой у вас и у сервера endianness ? Может быть, что разный?

**Comment by SergeyMirvoda** [comment]
На вставку гуида теста нет, есть только на чтение

https://github.com/Octonica/ClickHouseClient/blob/57eda1ea436f1ead6d308c4aac20a6831b3884f3/src/Octonica.ClickHouseClient.Tests/TypeTests.cs#L158

**Comment by f1lareon6** [comment]
Да, видел тест на чтение. На запись не нашел)

**Comment by victor-sushko** [comment]
@f1lareon6 
Добрый день.

Ошибка записи UUID исправлена в версии 1.1.13.

**Comment by victor-sushko** [comment]
> На вставку гуида теста нет, есть только на чтение

Формально тест на запись UUID есть, но фактически в нём проверятся только наличие бага в ClickHouse :(
https://github.com/Octonica/ClickHouseClient/blob/57eda1ea436f1ead6d308c4aac20a6831b3884f3/src/Octonica.ClickHouseClient.Tests/TypeTests.cs#L1429-L1436

> но с другой стороны FixedString это байты и если виноват порядок байтов FixedString наверное бы тоже пострадал

Напротив, если бы проблема была с порядком байт, то неправильно читалось бы вообще всё, кроме строк.

**Comment by f1lareon6** [comment]
@victor-sushko 
Благодарю вас за столь быстрое исправление.
