### ISSUE TITLE
Very slow "await reader.ReadAsync()"

### ISSUE THREAD

**Issue by valeravorobjev** [Octonica/ClickHouseClient#30]
Hello. It takes me a very long time to read the data. At the same time, the code in the loop practically does not affect the execution speed. 

`                    await using ClickHouseDataReader reader = await cmd.ExecuteReaderAsync();
                    while (await reader.ReadAsync())
                    {
                           ... get data
                    }`

For example this python code. it works much faster. 3-4 times faster. The request text is the same.

`result = client.execute(query)`

**Comment by victor-sushko** [comment]
Hello.

Could you please provide more information about your query? How many columns and rows are selected? What are the types of selected columns?

> At the same time, the code in the loop practically does not affect the execution speed.

It's exactly how the reader should work. `ReadAsync` fetches a block of columns from the network and stores it in a temporary buffer. This is the most time-consuming operation.

As I may guess, the code in the loop just reads the data from this buffer, so it works fast.

**Comment by valeravorobjev** [comment]
I'm using a very simple query. It reads about 20 columns. Double data types.

This code on C# very slow.

`await using ClickHouseDataReader reader = await cmd.ExecuteReaderAsync(); while (await reader.ReadAsync()) { ... get data }`

Even if you leave the loop (while) body empty. Still very slow.

And here is the python code. Which reads data with a single command works fast. About 5 times faster.

`result = client.execute(query)`

Reading from the clickhouse buffer is excluded.

**Comment by victor-sushko** [comment]
I wrote two tiny programs to measure performance of reading. They didn't show significant difference in performance between C# and Python. C# version even works faster. The query is the same in both cases:
```SQL
SELECT
  number AS c0,
  number/10.5 AS c1,
  number*3.1415926 AS c2,
  c1 AS c3,
  c2 AS c4,
  c1 AS c5
  c2 AS c6,
  toString(c0) AS c7
FROM system.numbers
LIMIT 2500000
```

Here is a program written in Python:
```Python
from clickhouse_driver import Client
import datetime

client = Client('localhost')
print("#\tRows\tElapsed")
count = 0
totalTime = 0
for x in range(0, 50):
	start = datetime.datetime.now()
	rows = client.execute('SELECT number AS c0, number/10.5 AS c1, number*3.1415926 AS c2, c1 AS c3, c2 AS c4, c1 AS c5, c2 AS c6, toString(c0) AS c7 FROM system.numbers LIMIT 2500000')
	end = datetime.datetime.now()
	count = count + 1
	totalTime += (end - start).total_seconds()
	print(str(x) + "\t" + str(len(rows)) + "\t" + str(end -start))

average = totalTime/count
print("Avg: " + str(average))

```

And here is an equivalent program written in C#:
```C#
using System;
using System.Threading.Tasks;
using Octonica.ClickHouseClient;

namespace Test { class Program {

static async Task Main(string[] args)
{
	await using var connection = new ClickHouseConnection("Host=localhost");
	await connection.OpenAsync();

	Console.WriteLine("#\tRows\tElapsed");
	var totalTime = 0d;
	int count;
	for(count = 0; count < 50; count++)
	{
		var d1 = DateTime.Now;
		var cmd = connection.CreateCommand("SELECT number AS c0, number/10.5 AS c1, number*3.1415926 AS c2, c1 AS c3, c2 AS c4, c1 AS c5, c2 AS c6, toString(c0) AS c7 FROM system.numbers LIMIT 2500000");
		await using var reader = await cmd.ExecuteReaderAsync();

		int rowCount = 0;
		while(await reader.ReadAsync())
			++rowCount;

		var d2 = DateTime.Now;

		totalTime += (d2 - d1).TotalSeconds;
		Console.WriteLine($"{count}\t{rowCount}\t{d2 - d1}");
	}

	var average = totalTime / count;
	Console.WriteLine($"Avg: {average}");
}

}}
```

**Comment by victor-sushko** [comment]
The issue was closed because I couldn't write a query which is working significantly slower in C# than in Python. Such query is required for further discussion of `ClickHouseDataReader`'s performance issues.
