### ISSUE TITLE
Map(key, value) type support

### ISSUE THREAD

**Issue by TuoNiao** [Octonica/ClickHouseClient#31]
hello, 
Is Map(key, value) type supported?
It looks like a very important feature. Please provider help.

**Comment by victor-sushko** [comment]
Hello, @TuoNiao!

`Map` is not currently supported. It's an experimental feature, but it seems stable.
I am going to add support for `Map` to the next version of ClickHouseClient.

**Comment by victor-sushko** [comment]
The type `Map(key, value)` is supported in the version 1.2.1.
