### ISSUE TITLE
Unable to cast object of type 'System.DateTime' to type 'System.DateTimeOffset'.

### ISSUE THREAD

**Issue by wilsonliu78** [Octonica/ClickHouseClient#32]
Unable to cast object of type 'System.DateTime' to type 'System.DateTimeOffset'.

**Comment by victor-sushko** [comment]
Hello, @wilsonliu78!

Could you please provide more details? It would be useful if you could provide a stack trace or a snippet of code caused this error.

**Comment by Teeeto** [comment]
I remember I encountered something like  this once.
While cannot produce the code - when selecting a clickhouse field of type DateTime32 (the one with second resolution) it comes as DateTimeOffsetType internally and you have to do something like 
((DateTimeOffset)MyRow[0]).DateTime

**Comment by victor-sushko** [comment]
There may be some confusion between ClickHouse types `Date` and `DateTime`.

The type `Date` for the lack of better choice is mapped to the .NET type `System.DateTime`. The time part is always 00:00:00 for values of this type. This behavior most likely will be changed (#33).

The type `DateTime` is mapped to the .NET type `System.DateTimeOffset`. This type preserves the original timezone's offset. And ClickHouse always provides `DateTime` with timezone.

Here is an example of reading `DateTime`:
```C#
var cmd = connection.CreateCommand("SELECT now()");
await using var reader = await cmd.ExecuteReaderAsync();
await reader.ReadAsync();

// It works
var dateTime = reader.GetDateTime(0);

// It also works
dateTime = ((DateTimeOffset) reader.GetValue(0)).DateTime;

// Throws System.InvalidCastException (Unable to cast object of type 'System.DateTimeOffset' to type 'System.DateTime')
dateTime = (DateTime) reader.GetValue(0);
```

And here is an example of reading `Date`:
```C#
var cmd = connection.CreateCommand("SELECT today()");
await using var reader = await cmd.ExecuteReaderAsync();
await reader.ReadAsync();

// It works
var dateTime = reader.GetDateTime(0);

// Now it works
dateTime = (DateTime) reader.GetValue(0);

// Throws System.InvalidCastException (Unable to cast object of type 'System.DateTime' to type 'System.DateTimeOffset')
dateTime = ((DateTimeOffset) reader.GetValue(0)).DateTime;
```
