### ISSUE TITLE
Throws exception "The value is null" when tries to get an empty string

### ISSUE THREAD

**Issue by MaxLevs** [Octonica/ClickHouseClient#37]
I have not-null column named "http_method" with string type. Some values in that column can be empty string. 
When I try to get value of that column on some iteraton of read loop, it throws the "The value is null" exception.

Actual behaviour: Throws exception

Expected behaviour: Returns string.Empty.

**Comment by SergeyMirvoda** [comment]
@MaxLevs 
Can you please attach the stack trace?

**Comment by MaxLevs** [comment]
> @MaxLevs Can you please attach the stack trace?

This exception was originally thrown at this call stack:
    [External Code]
    Test.ClickHouseClient.Program.Main(string[]) in Program.cs
    [External Code]

**Comment by SergeyMirvoda** [comment]
this is call stack, we need Stack Trace

The simplest way to get stack trace is to wrap your code into
```
try {
  //you code
} 
catch (Exception ex){
  Console.Write(ex.ToString());
}
```

**Comment by MaxLevs** [comment]
```
Octonica.ClickHouseClient.Exceptions.ClickHouseException: The value is null.
   at Octonica.ClickHouseClient.ClickHouseDataReader.GetFieldValue[T](Int32 ordinal)
   at Octonica.ClickHouseClient.ClickHouseDataReader.GetString(Int32 ordinal)
   at Test.ClickHouseClient.Program.Main(String[] args) in C:\Users\mliven\source\repos\MentolDataBoardCH\Test.ClickHouseClient\Program.cs:line 47

**Comment by SergeyMirvoda** [comment]
Thank you, this is very strange. String column can not hold nulls https://github.com/Octonica/ClickHouseClient/blob/master/src/Octonica.ClickHouseClient/Types/StringTableColumnBase.cs#L42

Can you please share the column type of ``http_method`` column

You can get it via a query like this
```
select  toTypeName(http_method) from {your_table_name}
```

**Comment by MaxLevs** [comment]
It's `LowCardinality(String)`

**Comment by SergeyMirvoda** [comment]
>It's LowCardinality(String)

thanks

**Comment by victor-sushko** [comment]
@MaxLevs
The bug was fixed. Please, check the version [2.2.4-rc](https://www.nuget.org/packages/Octonica.ClickHouseClient/2.2.4-rc).

**Comment by MaxLevs** [comment]
It gets correctly now but there is another problem. May be send it as another issue.

**Comment by SergeyMirvoda** [comment]
>May be send it as another issue.

You are welcome)
