### ISSUE TITLE
There is no supertype for types String, UUID because some of them are String/FixedString and some of them are not

### ISSUE THREAD

**Issue by wilsonliu78** [Octonica/ClickHouseClient#41]
DB::Exception: There is no supertype for types String, UUID because some of them are String/FixedString and some of them are not
Octonica.ClickHouseClient.Exceptions.ClickHouseServerException: DB::Exception: There is no supertype for types String, UUID because some of them are String/FixedString and some of them are not

**Comment by SergeyMirvoda** [comment]
Hi!
Looks like an error is in your SQL code.
Something like this https://github.com/ClickHouse/ClickHouse/issues/27813
Can you execute SQL code via clickhouse CLI client?

**Comment by wilsonliu78** [comment]
thanks your reply , i found cause 

column datatype is string,  query parameter use  Guid  , it will failed! 

failed:
{ "UserId", new Guid("ad49f169-e607-11eb-91a7-42a68d1dd535")},
{ "TenantId",new Guid("8fad140e-67b4-11ec-b6d3-2a03e8deecca")}

success:
{ "UserId", "ad49f169-e607-11eb-91a7-42a68d1dd535"},
{ "TenantId","8fad140e-67b4-11ec-b6d3-2a03e8deecca"},
