### ISSUE TITLE
Bool type not supported in data reader

### ISSUE THREAD

**Issue by MaceWindu** [Octonica/ClickHouseClient#56]
```
ClickHouseException: The type "Bool" is not supported.
         at Octonica.ClickHouseClient.ClickHouseCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean ignoreProfileEvents, Boolean async, CancellationToken cancellationToken)
         at Octonica.ClickHouseClient.Utils.TaskHelper.WaitNonAsyncTask[T](ValueTask`1 task)
         at Octonica.ClickHouseClient.ClickHouseCommand.ExecuteDbDataReader(CommandBehavior behavior)
```

**Comment by kurudj** [comment]
@victor-sushko this issue is still showing up, is it planned to be fixed? thank you.

**Comment by SergeyMirvoda** [comment]
@kurudj looks like it is implemented in 630f41e referenced above.

**Comment by kurudj** [comment]
@SergeyMirvoda I'm on the latest version of the package and still getting this issue, weird

**Comment by SergeyMirvoda** [comment]
@kurudj 
Can you please attach a simple repro?
@victor-sushko Victor am I right, or we didn't release this yet?

**Comment by kurudj** [comment]
> @kurudj Can you please attach a simple repro? @victor-sushko Victor am I right, or we didn't release this yet?

I am unable to provide a repro, but all I'm doing is calling `cmd.ExecuteReaderAsync()` with a select query on a table that contains a bool column.

**Comment by kurudj** [comment]
Hello. Any updates on this? This issue is very frequent for my implementation, and I might need to switch to a different client instead.

**Comment by victor-sushko** [comment]
The version [2.2.10](https://www.nuget.org/packages/Octonica.ClickHouseClient/2.2.10) with support of the type `Bool` was released today.

**Comment by kurudj** [comment]
Thanks much @victor-sushko !
