### ISSUE TITLE
Bulk вставка дат

### ISSUE THREAD

**Issue by ptzremoute** [Octonica/ClickHouseClient#57]
Добрый день!
Планируем переход с ClickHouse.ADO на вашу библиотеку, но столкнулись с проблемой вставки дат.

Таблица в базе:
```
CREATE TABLE Statistics.UserDomain
(
    Date DateTime DEFAULT toDateTime(now(), 'UTC')
)
ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(Date)
ORDER BY Date
TTL Date + toIntervalMonth(6)
SETTINGS index_granularity = 8192
```

Пример вставки:
```cs
var writer = await _conn.CreateColumnWriterAsync("INSERT INTO UserDomain(Date) VALUES", default)

await writer.WriteTableAsync(new object[] {
					data.Select(el => el.Date)
				}, data.Length, default);
```
Поле `Date` имеет тип `DateTime` и содержит значение в UTC.
Но после выполнения запроса в базу сохраняется значение с учетом временной зоны сервера.
Есть ли возможность вставить дату не учитывая никак временных зон? Например, явно указать временную зону или передать `Unix Timestamp` в качестве значения?

**Comment by SergeyMirvoda** [comment]
>Добрый день! Планируем переход

велкам!

Вообще у нас поддерживаются  клиентские тайм зоны, т.е. если вы создадите DateTime с указанием таймзоны то он правильно уйдёт на сервер и там сохранится в таймзоне сервера.

Я понимаю проблемы, но не уважать таймзоны это путь в никуда)

Мы достаточно получили проблем при работе одновременно в 12 часовых поясах поэтому для себя выбрали два пути
1. Там где не нужны таймзоны ставим на клиенте и сервере одинаковые таймзоны (МСК например)
2. Во всех остальных местах используем таймзоны, да это не очень удобно, но защищает от кучи ошибок при расчётах всякого.

КликХаус не умеет без таймзон, если прям совсем никак то можно пойти по пути UinxTime))
