### ISSUE TITLE
Impossible to set allow_experimental_live_view setting for creating ClickHouse live views

### ISSUE THREAD

**Issue by Alex69rus** [Octonica/ClickHouseClient#61]
Hi All!

From code I apply migration scripts to ClickHouse server.
We use live view experimental feature.

Sample:
```csharp
public static async Task ApplyMigration(string connectionString)
{
    await using var dbConnection = new ClickHouseConnection(connectionString);
    await dbConnection.ExecuteAsync("CREATE LIVE VIEW lv WITH TIMEOUT 15 AND REFRESH 5 AS SELECT now();");
}
```

While creating live view I get error:
```
Octonica.ClickHouseClient.Exceptions.ClickHouseServerException
DB::Exception: Experimental LIVE VIEW feature is not enabled (the setting 'allow_experimental_live_view')
   at Octonica.ClickHouseClient.ClickHouseCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Octonica.ClickHouseClient.ClickHouseCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Octonica.ClickHouseClient.ClickHouseCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in /_/Dapper/SqlMapper.Async.cs:line 646
....
```

I've tried to find such setting at `ClickHouseConnectionStringBuilder` and `ClickHouseConnection` classes, but not found.

Is there a way to set this setting?

**Comment by flour** [comment]
You need to enable it with `set allow_experimental_live_view = 1` or config.xml on clickhouse itself and restart server (as mentioned in error log)

**Comment by Alex69rus** [comment]
Thanks for advise.

Is there a way to do in on client side for this sdk?
Because I did it with other sdk (ClickHouse.Client) on client side.

**Comment by SergeyMirvoda** [comment]
>Is there a way to do it on client side for this sdk?

AFAIK
you can execute `set` with the same session (connection)
something like this
```
await dbConnection.ExecuteAsync("set allow_experimental_live_view = 1;");
await dbConnection.ExecuteAsync("CREATE LIVE VIEW lv WITH TIMEOUT 15 AND REFRESH 5 AS SELECT now();");
```

**Comment by Alex69rus** [comment]
It doesn't work. Looks like this client works without sessions.

Do I need to enable session somewhere? 
I didn't find such settings at `ClickHouseConnectionStringBuilder`or at `ClickHouseConnection`.

**Comment by Alex69rus** [comment]
> await using var connection = await OpenConnectionAsync();

It helped. Now it works fine. Thank you!

Did I get it correctly, what `ClickHouseConnection` should be registered as Scoped/Transient in DI (according tcp connections and sessions) ?

Is it thread safe?
