### ISSUE TITLE
Asynchronous Inserts (async_insert)

### ISSUE THREAD

**Issue by xxramm16916** [Octonica/ClickHouseClient#72]
Hi. I'm sorry for asking the question here.
        
        I have same function:
        `
        await using var connection = new ClickHouseConnection(_connectionStringBuilder);
        await connection.OpenAsync(cancellationToken);

        await using ClickHouseColumnWriter writer = await connection
            .CreateColumnWriterAsync("INSERT INTO db.testtable(num, id, str) VALUES", cancellationToken);

        await writer.WriteTableAsync(definition.Data, definition.Count, cancellationToken);
        `
        

         I would like to throw request settings. INSERT INTO db.testtable(num, id, str) VALUES (...); settings insert_distributed_sync = 1;
         
         Is it possible to do this? Is it possible to set these settings for the connection?
         
         So, I need something like this documentation https://clickhouse.com/docs/en/cloud/bestpractices/asynchronous-inserts

**Comment by victor-sushko** [comment]
Hi!

You can execute the command `SET setting=value`. This command set the value of the property for the connection.

```C#
    await using var connection = new ClickHouseConnection(_connectionStringBuilder);
    await connection.OpenAsync(cancellationToken);

    var cmd = connection.CreateCommand();
    cmd.CommandText = "SET insert_distributed_sync = 1";
    await cmd.ExecuteNonQueryAsync(cancellationToken);

    await using ClickHouseColumnWriter writer = await connection
        .CreateColumnWriterAsync("INSERT INTO db.testtable(num, id, str) VALUES", cancellationToken);

    await writer.WriteTableAsync(definition.Data, definition.Count, cancellationToken);
```

**Comment by xxramm16916** [comment]
thank you)
