### ISSUE TITLE
Cannot perform simple select with integers

### ISSUE THREAD

**Issue by DarkWanderer** [Octonica/ClickHouseClient#8]
### Attempt 1:
```
using var reader = connection.ExecuteReader($"SELECT number FROM numbers(1000000)");
while (reader.Read())
    reader.GetInt32(0);
```
Result: `Unable to cast object of type 'System.UInt64' to type 'System.Int32'`

### Attempt 2:
```
using var reader = connection.ExecuteReader($"SELECT number FROM numbers(1000000)");
while (reader.Read())
    reader.GetInt64(0);
```
Result: `Unable to cast object of type 'System.UInt64' to type 'System.Int64'.`

While ADO.NET spec does not requre implicit conversion (e.g. `UInt64` => `Int32`), other clients do handle such situation

**Comment by SergeyMirvoda** [comment]
But what other clients do with overflows?
We can't safely cast UInt64 even into Int64.

**Comment by SergeyMirvoda** [comment]
FYI here is default type mapping docs https://github.com/Octonica/ClickHouseClient/blob/master/docs/TypeMapping.md

**Comment by SergeyMirvoda** [comment]
According to [Type Mapping docs](https://github.com/Octonica/ClickHouseClient/blob/master/docs/TypeMapping.md)
There is no implicit convert from ``uint64`` to ``int32`` and even to ``int64`` and it is your task to cast to less "wide" type.

Here are your examples corrected

```
using var reader = connection.ExecuteReader($"SELECT toInt32(number) FROM numbers(1000000)");
while (reader.Read())
    reader.GetInt32(0);
```

```
using var reader = connection.ExecuteReader($"SELECT number FROM numbers(1000000)");
while (reader.Read())
    reader.GetUInt64(0);
```

Yes, you have to know all of your numeric column types ahead of coding in c# something like that:

```
SELECT number as n, toColumnTypeName(n) FROM numbers(10)
```
