### ISSUE TITLE
Which protocol does ClickHouseClient use behind the scene?

### ISSUE THREAD

**Issue by Ceyword** [Octonica/ClickHouseClient#80]
Which protocol does ClickHouseClient use behind the scene?

Is it HTTP?

Are we limited to HTTP, since it has limited functionality?

**Comment by victor-sushko** [comment]
ClickHouseClient implements the [native](https://clickhouse.com/docs/en/interfaces/tcp) binary protocol.

> Are we limited to HTTP, since it has limited functionality?

Both HTTP and native TCP protocols have some limitations. The major feature missing in the native protocol is [FORMAT clause](https://clickhouse.com/docs/en/sql-reference/statements/select/format#implementation-details).
