### ISSUE TITLE
.NET 8 support?

### ISSUE THREAD

**Issue by jzabroski** [Octonica/ClickHouseClient#81]
Hi,

Currently using Trino (aka Starburst Galaxy) (fka Facebook Presto) for parallel data warehouse projects. The Trino client for .NET is not great. I was looking at alternatives and wanted to see how ClickHouse held up.  But seeing this nuget package has not been published for 1 year is a bit depressing.

What's the deal?  Can I help get this moving again?  If the code is better than the current .NET Trino client (which is very slow and not a great client-facing API), it may not be a bad decision to help out here.

**Comment by SergeyMirvoda** [comment]
No depression. We just finished what we wanted)
On older versions of CH, our library works fine and for our projects (we develop ELT\DW\OLAP tools) it was just enough functionality.

We are currently updating the library to support the current versions of CH. The guys from ClickHouse completely changed the binary representation of the parameters in the protocol, so it took some time.

In a few days we are going to release a version with support for the current versions of ClickHouse, and then we will switch to dotnet 8


Thank you for your interest)

**Comment by jzabroski** [comment]
Sweet! Let me know if I can help today and tomorrow. I'm off from work. Even if it's just test coverage.
