### ISSUE TITLE
New ClickHouse type

### ISSUE THREAD

**Issue by ridicoulous** [Octonica/ClickHouseClient#84]
In new database version was shipped new experimental data type, [Variant](https://clickhouse.com/docs/en/sql-reference/data-types/variant). Is it any plans to implement it?

**Comment by SergeyMirvoda** [comment]
@ridicoulous 
I wonder how you plan to use it?
Looks like you can't select whole table without type checks.
Maybe writing Variants?

**Comment by victor-sushko** [comment]
The version [3.1.3](https://www.nuget.org/packages/Octonica.ClickHouseClient/3.1.3) with support of new type `Variant(T1, ... , Tn)` was released.
