### ISSUE TITLE
TODO: add support for custom serialization exception when read bool column type

### ISSUE THREAD

**Issue by DevDmitryN** [Octonica/ClickHouseClient#85]
I try read bool column type, but get NotImplementedException "TODO: add support for custom serialization.". In same time nullable bool column type works fine.

Can you solve this problem?

FROM YOUR SOURCE CODE:

ClickHouseTcpClient row 421

```
if (_client.ServerInfo.Revision >= ClickHouseProtocolRevisions.MinRevisionWithCustomSerialization)
{
     var hasCustom = await reader.ReadBool(async, cancellationToken);
      if (hasCustom)
          throw new NotImplementedException("TODO: add support for custom serialization.");
}
```

PS: clickhouse version 24.1.5.6

**Comment by alec-anikin** [comment]
It's sparse column serialization issue which was enabled by default in v23.7+ 
As a workaround, you can disable it on the server: see more about merge tree option  **ratio_of_defaults_for_sparse_serialization**

**Comment by valeravorobjev** [comment]
Not only a Boolean value. I've got an integer column with zero value (0) or column array of integers. And I get this error in both cases. Yes, setting the value of ratio_of_defaults_for_sparse_serialization=1.0 helps me when creating a table, but this is a bad way to solve the problem

**Comment by valeravorobjev** [comment]
Clickhouse latest version

**Comment by victor-sushko** [comment]
The bug was fixed in the version [3.1.2](https://www.nuget.org/packages/Octonica.ClickHouseClient/3.1.2).

**Comment by Yerkon** [comment]
@victor-sushko, Is any change log will be added to see changes, improvements, some breaking list? 
Is it safe to upgrade for the latest version ?

**Comment by victor-sushko** [comment]
> Is any change log will be added to see changes, improvements, some breaking list?

I updated the changelog, but have not merged it to the main branch yet.
https://github.com/Octonica/ClickHouseClient/blob/v3.1.2/CHANGELOG.md

> Is it safe to upgrade for the latest version ?

Yes, it should be safe. There were mostly additions for the sparse serialization mode.
